<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Language', 'yozoa');

/**
 * BaseLanguage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $culture
 * @property string $name
 * @property string $prefferred_currency
 * @property Doctrine_Collection $User
 * 
 * @method string              getCulture()             Returns the current record's "culture" value
 * @method string              getName()                Returns the current record's "name" value
 * @method string              getPrefferredCurrency()  Returns the current record's "prefferred_currency" value
 * @method Doctrine_Collection getUser()                Returns the current record's "User" collection
 * @method Language            setCulture()             Sets the current record's "culture" value
 * @method Language            setName()                Sets the current record's "name" value
 * @method Language            setPrefferredCurrency()  Sets the current record's "prefferred_currency" value
 * @method Language            setUser()                Sets the current record's "User" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLanguage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('language');
        $this->hasColumn('culture', 'string', 2, array(
             'type' => 'string',
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('prefferred_currency', 'string', 3, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('User', array(
             'local' => 'culture',
             'foreign' => 'language'));
    }
}