<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HelpCategory', 'yozoa');

/**
 * BaseHelpCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $sort_order
 * @property Doctrine_Collection $HelpTopic
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getSortOrder()  Returns the current record's "sort_order" value
 * @method Doctrine_Collection getHelpTopic()  Returns the current record's "HelpTopic" collection
 * @method HelpCategory        setId()         Sets the current record's "id" value
 * @method HelpCategory        setName()       Sets the current record's "name" value
 * @method HelpCategory        setSortOrder()  Sets the current record's "sort_order" value
 * @method HelpCategory        setHelpTopic()  Sets the current record's "HelpTopic" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHelpCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('help_category');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sort_order', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('HelpTopic', array(
             'local' => 'id',
             'foreign' => 'help_category_id'));
    }
}