<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Currency', 'yozoa');

/**
 * BaseCurrency
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $code
 * @property string $name
 * @property string $symbol
 * @property float $value
 * @property timestamp $updated_at
 * 
 * @method string    getCode()       Returns the current record's "code" value
 * @method string    getName()       Returns the current record's "name" value
 * @method string    getSymbol()     Returns the current record's "symbol" value
 * @method float     getValue()      Returns the current record's "value" value
 * @method timestamp getUpdatedAt()  Returns the current record's "updated_at" value
 * @method Currency  setCode()       Sets the current record's "code" value
 * @method Currency  setName()       Sets the current record's "name" value
 * @method Currency  setSymbol()     Sets the current record's "symbol" value
 * @method Currency  setValue()      Sets the current record's "value" value
 * @method Currency  setUpdatedAt()  Sets the current record's "updated_at" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCurrency extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('currency');
        $this->hasColumn('code', 'string', 3, array(
             'type' => 'string',
             'primary' => true,
             'length' => 3,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('symbol', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('value', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}