<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AttributeValues', 'yozoa');

/**
 * BaseAttributeValues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $attribute_id
 * @property string $value
 * @property integer $sort_order
 * @property Attribute $Attribute
 * @property Doctrine_Collection $ProductAttribute
 * @property Doctrine_Collection $I18nAttributeValues
 * @property Doctrine_Collection $ProductAttributeValue
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getAttributeId()           Returns the current record's "attribute_id" value
 * @method string              getValue()                 Returns the current record's "value" value
 * @method integer             getSortOrder()             Returns the current record's "sort_order" value
 * @method Attribute           getAttribute()             Returns the current record's "Attribute" value
 * @method Doctrine_Collection getProductAttribute()      Returns the current record's "ProductAttribute" collection
 * @method Doctrine_Collection getI18nAttributeValues()   Returns the current record's "I18nAttributeValues" collection
 * @method Doctrine_Collection getProductAttributeValue() Returns the current record's "ProductAttributeValue" collection
 * @method AttributeValues     setId()                    Sets the current record's "id" value
 * @method AttributeValues     setAttributeId()           Sets the current record's "attribute_id" value
 * @method AttributeValues     setValue()                 Sets the current record's "value" value
 * @method AttributeValues     setSortOrder()             Sets the current record's "sort_order" value
 * @method AttributeValues     setAttribute()             Sets the current record's "Attribute" value
 * @method AttributeValues     setProductAttribute()      Sets the current record's "ProductAttribute" collection
 * @method AttributeValues     setI18nAttributeValues()   Sets the current record's "I18nAttributeValues" collection
 * @method AttributeValues     setProductAttributeValue() Sets the current record's "ProductAttributeValue" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAttributeValues extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attribute_values');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('attribute_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('sort_order', 'integer', 2, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Attribute', array(
             'local' => 'attribute_id',
             'foreign' => 'id'));

        $this->hasMany('ProductAttribute', array(
             'refClass' => 'ProductAttributeValue',
             'local' => 'attribute_value_id',
             'foreign' => 'product_attribute_id'));

        $this->hasMany('I18nAttributeValues', array(
             'local' => 'id',
             'foreign' => 'attr_value_id'));

        $this->hasMany('ProductAttributeValue', array(
             'local' => 'id',
             'foreign' => 'attribute_value_id'));
    }
}