<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('HelpTopic', 'yozoa');

/**
 * BaseHelpTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $question
 * @property string $answer
 * @property integer $sort_order
 * @property integer $help_category_id
 * @property integer $read_count
 * @property HelpCategory $HelpCategory
 * 
 * @method integer      getId()               Returns the current record's "id" value
 * @method string       getQuestion()         Returns the current record's "question" value
 * @method string       getAnswer()           Returns the current record's "answer" value
 * @method integer      getSortOrder()        Returns the current record's "sort_order" value
 * @method integer      getHelpCategoryId()   Returns the current record's "help_category_id" value
 * @method integer      getReadCount()        Returns the current record's "read_count" value
 * @method HelpCategory getHelpCategory()     Returns the current record's "HelpCategory" value
 * @method HelpTopic    setId()               Sets the current record's "id" value
 * @method HelpTopic    setQuestion()         Sets the current record's "question" value
 * @method HelpTopic    setAnswer()           Sets the current record's "answer" value
 * @method HelpTopic    setSortOrder()        Sets the current record's "sort_order" value
 * @method HelpTopic    setHelpCategoryId()   Sets the current record's "help_category_id" value
 * @method HelpTopic    setReadCount()        Sets the current record's "read_count" value
 * @method HelpTopic    setHelpCategory()     Sets the current record's "HelpCategory" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHelpTopic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('help_topic');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('question', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('answer', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('sort_order', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('help_category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('read_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('HelpCategory', array(
             'local' => 'help_category_id',
             'foreign' => 'id'));
    }
}