<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Ipcountry', 'yozoa');

/**
 * BaseIpcountry
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $ip_from
 * @property string $ip_to
 * @property string $country_iso1
 * @property string $country_iso2
 * @property string $country_long
 * 
 * @method string    getIpFrom()       Returns the current record's "ip_from" value
 * @method string    getIpTo()         Returns the current record's "ip_to" value
 * @method string    getCountryIso1()  Returns the current record's "country_iso1" value
 * @method string    getCountryIso2()  Returns the current record's "country_iso2" value
 * @method string    getCountryLong()  Returns the current record's "country_long" value
 * @method Ipcountry setIpFrom()       Sets the current record's "ip_from" value
 * @method Ipcountry setIpTo()         Sets the current record's "ip_to" value
 * @method Ipcountry setCountryIso1()  Sets the current record's "country_iso1" value
 * @method Ipcountry setCountryIso2()  Sets the current record's "country_iso2" value
 * @method Ipcountry setCountryLong()  Sets the current record's "country_long" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIpcountry extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ipcountry');
        $this->hasColumn('ip_from', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('ip_to', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('country_iso1', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('country_iso2', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 5,
             ));
        $this->hasColumn('country_long', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}