<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('I18nAttribute', 'yozoa');

/**
 * BaseI18nAttribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $attribute_id
 * @property string $culture
 * @property string $name
 * @property string $hint
 * @property Attribute $Attribute
 * 
 * @method integer       getAttributeId()  Returns the current record's "attribute_id" value
 * @method string        getCulture()      Returns the current record's "culture" value
 * @method string        getName()         Returns the current record's "name" value
 * @method string        getHint()         Returns the current record's "hint" value
 * @method Attribute     getAttribute()    Returns the current record's "Attribute" value
 * @method I18nAttribute setAttributeId()  Sets the current record's "attribute_id" value
 * @method I18nAttribute setCulture()      Sets the current record's "culture" value
 * @method I18nAttribute setName()         Sets the current record's "name" value
 * @method I18nAttribute setHint()         Sets the current record's "hint" value
 * @method I18nAttribute setAttribute()    Sets the current record's "Attribute" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseI18nAttribute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('i18n_attribute');
        $this->hasColumn('attribute_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('culture', 'string', 5, array(
             'type' => 'string',
             'primary' => true,
             'length' => 5,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('hint', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Attribute', array(
             'local' => 'attribute_id',
             'foreign' => 'id'));
    }
}