<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ProductAttribute', 'yozoa');

/**
 * BaseProductAttribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_id
 * @property integer $attribute_id
 * @property string $attribute_value
 * @property Product $Product
 * @property Attribute $Attribute
 * @property Doctrine_Collection $AttributeValues
 * @property Doctrine_Collection $ProductAttributeValue
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method integer             getProductId()             Returns the current record's "product_id" value
 * @method integer             getAttributeId()           Returns the current record's "attribute_id" value
 * @method string              getAttributeValue()        Returns the current record's "attribute_value" value
 * @method Product             getProduct()               Returns the current record's "Product" value
 * @method Attribute           getAttribute()             Returns the current record's "Attribute" value
 * @method Doctrine_Collection getAttributeValues()       Returns the current record's "AttributeValues" collection
 * @method Doctrine_Collection getProductAttributeValue() Returns the current record's "ProductAttributeValue" collection
 * @method ProductAttribute    setId()                    Sets the current record's "id" value
 * @method ProductAttribute    setProductId()             Sets the current record's "product_id" value
 * @method ProductAttribute    setAttributeId()           Sets the current record's "attribute_id" value
 * @method ProductAttribute    setAttributeValue()        Sets the current record's "attribute_value" value
 * @method ProductAttribute    setProduct()               Sets the current record's "Product" value
 * @method ProductAttribute    setAttribute()             Sets the current record's "Attribute" value
 * @method ProductAttribute    setAttributeValues()       Sets the current record's "AttributeValues" collection
 * @method ProductAttribute    setProductAttributeValue() Sets the current record's "ProductAttributeValue" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductAttribute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_attribute');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('attribute_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('attribute_value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id'));

        $this->hasOne('Attribute', array(
             'local' => 'attribute_id',
             'foreign' => 'id'));

        $this->hasMany('AttributeValues', array(
             'refClass' => 'ProductAttributeValue',
             'local' => 'product_attribute_id',
             'foreign' => 'attribute_value_id'));

        $this->hasMany('ProductAttributeValue', array(
             'local' => 'id',
             'foreign' => 'product_attribute_id'));
    }
}