<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('XAreaLocation', 'yozoa');

/**
 * BaseXAreaLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $parent_id
 * @property string $name
 * @property float $map_lat
 * @property float $map_lng
 * @property XArea $XArea
 * @property Doctrine_Collection $Product
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method integer             getParentId()  Returns the current record's "parent_id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method float               getMapLat()    Returns the current record's "map_lat" value
 * @method float               getMapLng()    Returns the current record's "map_lng" value
 * @method XArea               getXArea()     Returns the current record's "XArea" value
 * @method Doctrine_Collection getProduct()   Returns the current record's "Product" collection
 * @method XAreaLocation       setId()        Sets the current record's "id" value
 * @method XAreaLocation       setParentId()  Sets the current record's "parent_id" value
 * @method XAreaLocation       setName()      Sets the current record's "name" value
 * @method XAreaLocation       setMapLat()    Sets the current record's "map_lat" value
 * @method XAreaLocation       setMapLng()    Sets the current record's "map_lng" value
 * @method XAreaLocation       setXArea()     Sets the current record's "XArea" value
 * @method XAreaLocation       setProduct()   Sets the current record's "Product" collection
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseXAreaLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('x_area_location');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('map_lat', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('map_lng', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('XArea', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('Product', array(
             'local' => 'id',
             'foreign' => 'x_area_location_id'));
    }
}