<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Guestbook', 'yozoa');

/**
 * BaseGuestbook
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $body
 * @property string $email
 * @property timestamp $created_at
 * @property integer $confirmed
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method string    getName()       Returns the current record's "name" value
 * @method string    getBody()       Returns the current record's "body" value
 * @method string    getEmail()      Returns the current record's "email" value
 * @method timestamp getCreatedAt()  Returns the current record's "created_at" value
 * @method integer   getConfirmed()  Returns the current record's "confirmed" value
 * @method Guestbook setId()         Sets the current record's "id" value
 * @method Guestbook setName()       Sets the current record's "name" value
 * @method Guestbook setBody()       Sets the current record's "body" value
 * @method Guestbook setEmail()      Sets the current record's "email" value
 * @method Guestbook setCreatedAt()  Sets the current record's "created_at" value
 * @method Guestbook setConfirmed()  Sets the current record's "confirmed" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGuestbook extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('guestbook');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('confirmed', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}