<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PriceFormat', 'yozoa');

/**
 * BasePriceFormat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $x_area_id
 * @property string $currency_main
 * @property float $price_original
 * @property float $price_global
 * @property string $description
 * @property Category $Category
 * @property XArea $XArea
 * 
 * @method integer     getCategoryId()     Returns the current record's "category_id" value
 * @method integer     getXAreaId()        Returns the current record's "x_area_id" value
 * @method string      getCurrencyMain()   Returns the current record's "currency_main" value
 * @method float       getPriceOriginal()  Returns the current record's "price_original" value
 * @method float       getPriceGlobal()    Returns the current record's "price_global" value
 * @method string      getDescription()    Returns the current record's "description" value
 * @method Category    getCategory()       Returns the current record's "Category" value
 * @method XArea       getXArea()          Returns the current record's "XArea" value
 * @method PriceFormat setCategoryId()     Sets the current record's "category_id" value
 * @method PriceFormat setXAreaId()        Sets the current record's "x_area_id" value
 * @method PriceFormat setCurrencyMain()   Sets the current record's "currency_main" value
 * @method PriceFormat setPriceOriginal()  Sets the current record's "price_original" value
 * @method PriceFormat setPriceGlobal()    Sets the current record's "price_global" value
 * @method PriceFormat setDescription()    Sets the current record's "description" value
 * @method PriceFormat setCategory()       Sets the current record's "Category" value
 * @method PriceFormat setXArea()          Sets the current record's "XArea" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePriceFormat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('price_format');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('x_area_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('currency_main', 'string', 4, array(
             'type' => 'string',
             'default' => 'USD',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('price_original', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('price_global', 'float', null, array(
             'type' => 'float',
             'default' => 0,
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('XArea', array(
             'local' => 'x_area_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}