<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('I18nCategory', 'yozoa');

/**
 * BaseI18nCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $culture
 * @property string $name
 * @property Category $Category
 * 
 * @method integer      getCategoryId()  Returns the current record's "category_id" value
 * @method string       getCulture()     Returns the current record's "culture" value
 * @method string       getName()        Returns the current record's "name" value
 * @method Category     getCategory()    Returns the current record's "Category" value
 * @method I18nCategory setCategoryId()  Sets the current record's "category_id" value
 * @method I18nCategory setCulture()     Sets the current record's "culture" value
 * @method I18nCategory setName()        Sets the current record's "name" value
 * @method I18nCategory setCategory()    Sets the current record's "Category" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseI18nCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('i18n_category');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('culture', 'string', 5, array(
             'type' => 'string',
             'primary' => true,
             'length' => 5,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));
    }
}