<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('I18nAttributeValues', 'yozoa');

/**
 * BaseI18nAttributeValues
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $attr_value_id
 * @property string $culture
 * @property string $value
 * @property AttributeValues $AttributeValues
 * 
 * @method integer             getAttrValueId()     Returns the current record's "attr_value_id" value
 * @method string              getCulture()         Returns the current record's "culture" value
 * @method string              getValue()           Returns the current record's "value" value
 * @method AttributeValues     getAttributeValues() Returns the current record's "AttributeValues" value
 * @method I18nAttributeValues setAttrValueId()     Sets the current record's "attr_value_id" value
 * @method I18nAttributeValues setCulture()         Sets the current record's "culture" value
 * @method I18nAttributeValues setValue()           Sets the current record's "value" value
 * @method I18nAttributeValues setAttributeValues() Sets the current record's "AttributeValues" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Sagar S. Deshmukh
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseI18nAttributeValues extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('i18n_attribute_values');
        $this->hasColumn('attr_value_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('culture', 'string', 5, array(
             'type' => 'string',
             'primary' => true,
             'length' => 5,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AttributeValues', array(
             'local' => 'attr_value_id',
             'foreign' => 'id'));
    }
}