# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    login_module:           user
    login_action:           login

    secure_module:          user
    secure_action:          login
  .settings:
    charset: utf-8
    i18n: on
    default_culture: no_NO
    # Form security secret (CSRF protection)
#    csrf_secret:            767b8d0ea129c4d9623a31d9f88e3f9ed193768d
    csrf_secret:            false

    # Output escaping settings
#    escaping_strategy:      true
    escaping_strategy:      false
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    standard_helpers:       [Partial, Cache, Global, I18N]
