<?php



/**

 * Banner

 * 

 * This class has been auto-generated by the Doctrine ORM Framework

 * 

 * @package    yozoa

 * @subpackage model

 * @author     Falcon

 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $

 */

class Banner extends BaseBanner

{

  public function getColor()

  {

    $today = date("Y-m-d");

    $start_date = $this->getBeginDate();

    $end_date = $this->getEndDate();

    

    if($end_date < $today)

    { 

      return "#ddd"; // paste

    }

    elseif($start_date > $today)

    {

      return "#ffffcc"; // future

    }

    elseif(($start_date <= $today) && ($end_date >= $today)) 

    {

      return "F6F6F6"; // nowadays

    }

    

    return "#ddd"; // wrong date

  }

}