<?php

/**
 * CountryLangCurrTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CountryLangCurrTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CountryLangCurrTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CountryLangCurr');
    }
	
	public function getCountryLanguageAndCurrency($countryCode)
    {
        $q = Doctrine_Query::create()
                ->select('clc.*')
                ->from('CountryLangCurr AS clc')
                ->where('clc.country_code = ?', $countryCode);
        return $q->execute();
    }
}