<?php



/**

 * Guestbook

 * 

 * This class has been auto-generated by the Doctrine ORM Framework

 * 

 * @package    yozoa

 * @subpackage model

 * @author     Falcon

 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $

 */

class Guestbook extends BaseGuestbook

{

    public function save(Doctrine_Connection $conn = null)

      {

        if ($this->isNew())

        {

          $this->setCreatedAt(date("Y-m-d H:i:s", time()));

        }

        return parent::save($conn);

      }

}