<?php

/**
 * I18nCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    yozoa
 * @subpackage model
 * @author     Falcon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class I18nCategory extends BaseI18nCategory
{

}