<?php

/**
 * IpcountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IpcountryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IpcountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ipcountry');
    }
	
	public function convertIP($ip_addr)
    {
        list($ip_p1,$ip_p2,$ip_p3,$ip_p4) = explode(".",$ip_addr);
        $sum1 = $ip_p1 * 256 + $ip_p2;
        $sum2 = $sum1*256  + $ip_p3;
        $ip_decimal = $sum2*256  + $ip_p4;
        return $ip_decimal;
    }
	
	public function getCountryCode($ipAddress)
    {
		$ipAddress = self::getInstance()->convertIP($ipAddress);
        $q = Doctrine_Query::create()
                ->select('ip.country_iso1')
                ->from('Ipcountry AS ip')
                ->where('ip.ip_from <= ?', $ipAddress)
                ->andWhere('ip.ip_to >= ?', $ipAddress);
        return $q->execute();

    }

}