<?php



/**

 * ProductAttribute

 *

 * This class has been auto-generated by the Doctrine ORM Framework

 *

 * @package    yozoa

 * @subpackage model

 * @author     Falcon

 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $

 */

class ProductAttribute extends BaseProductAttribute

{

  private $_attribute;

  public function getAttributeObject($culture = "")

  {

    if (!isset($this->_attribute))

    {

      $q = Doctrine_Query::create()

          ->select('a.*')

          ->addSelect('COALESCE(ia.name, a.name) AS name')

          ->addSelect('COALESCE(ia.hint, a.hint) AS hint')

          ->from('Attribute a')

          ->leftJoin('a.I18nAttribute ia WITH ia.culture = ?', $culture)

          ->where('a.id = ?', $this->getAttributeId());



      $this->_attribute = $q->fetchOne();

    }

    return $this->_attribute;

  }

  public function setAttributeObject(Attribute $attribute)

  {

    $this->_attribute = $attribute;

  }



  public function getProductAttributeValues($include_null = true, $culture = "")

  {

    //$pav_id, $a_id, $include_null = true

    return Doctrine::getTable('AttributeValues')

            ->getProductAttributeValues($this->getId(), $this->getAttributeId(), $include_null, $culture);

  }

}

