<?php

/**
 * XArea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    yozoa
 * @subpackage model
 * @author     Falcon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class XArea extends BaseXArea
{

    /**
   * Checking is leaf
   * @return <type>
   */
  public function isLeaf()
  {
    return $this->getRgt() - $this->getLft() == 1 ? true : false;
  }

  public function save(Doctrine_Connection $conn = null)
  {
    //is new
    if ($this->isNew())
    {
      //parent
      $pXArea = $this->getXArea();

      Doctrine_Query::create()
          ->update('XArea x')
          ->set('x.lft', 'x.lft + 2')
          ->where('x.lft > ?', $pXArea->getRgt())
          ->execute();
      
      Doctrine_Query::create()
          ->update('XArea x')
          ->set('x.rgt', 'x.rgt + 2')
          ->where('x.rgt >= ?', $pXArea->getRgt())
          ->execute();

      $this->setLft($pXArea->getRgt());
      $this->setRgt($pXArea->getRgt() + 1);
      $this->setLvl($pXArea->getLvl() + 1);
    }
    return parent::save($conn);
  }

  public function delete(Doctrine_Connection $conn = null)
  {
    $lft = $this->getLft();
    $rgt = $this->getRgt();
    $width = $rgt - $lft + 1;

    if (is_null($conn))
    {
      $conn = $this->getTable()->getConnection();
    }

    Doctrine_Query::create($conn)
        ->delete('XArea x')
        ->where("x.lft BETWEEN ? AND ?", array($lft, $rgt))
        ->execute();

    Doctrine_Query::create($conn)
        ->update('XArea x')
        ->set('x.rgt', "x.rgt - {$width}")
        ->where('x.rgt > ?', $rgt)
        ->execute();

    Doctrine_Query::create($conn)
        ->update('XArea x')
        ->set('x.lft', "x.lft - {$width}")
        ->where('x.lft > ?', $rgt)
        ->execute();

    return parent::delete($conn);
  }

}