<?php

/**
 * XAreaLocationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class XAreaLocationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object XAreaLocationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('XAreaLocation');
    }
	
	public function getChildrens($xAreaId)
    {

        return Doctrine_Query::create()

			->from('XAreaLocation x')
	
			->where('x.parent_id = ?', $xAreaId)
	
			->andWhere('x.id <> 0')
	
			->execute();

    }
}