editSuccess:
  stylesheets:    [flick/jquery-ui-1.7.2.custom.css]
  javascripts:    [ui/ui.core.min.js, ui/ui.dialog.min.js,/js/fckeditor/fckeditor.js]

newSuccess:
  stylesheets:    [flick/jquery-ui-1.7.2.custom.css]
  javascripts:    [ui/ui.core.min.js, ui/ui.dialog.min.js,/js/fckeditor/fckeditor.js]
 
indexSuccess:
  stylesheets:    [flick/jquery-ui-1.7.2.custom.css]
  javascripts:    [ui/ui.core.min.js, ui/ui.dialog.min.js,ui/ui.draggable.min.js, /js/fckeditor/fckeditor.js]
  metas:
    title:        Guestbook
