## YAML Template.
showSuccess:
  stylesheets:    [colorbox.css]
  javascripts:    [jquery.colorbox.js]
  
searchSuccess:
  javascripts:    [jquery.highlight-1.1.js]

indexSuccess:
  stylesheets:    [jquery.jcarousel.css,skins.css,store-skins.css]
  javascripts:    [jquery.jcarousel.pack.js]

albumSuccess:
  stylesheets:    [flick/jquery-ui-1.7.2.custom.css]
  javascripts:    [ui/ui.core.min.js,ui/ui.dialog.min.js,ui/ui.draggable.min.js,imageviewer/test.js]